# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  secret_key_base: f9473c03d61753beefc941e94f5b642785bbd4cc5d231c4a2713cec05a1c9a46fcbfea2c84483192f15fa3adde7a98cb3d8b88c67d2b34c704793985d5348e93

test:
  secret_key_base: c9fdf749c85347932251d3fb324cdca0159ed6636a1ba54bc18c57f224b5f29b16da256ebd8a574df8d6cc843efacb565e1c78dacdf1a08ba58f9352f49b724b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
